<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['pais' => 'Afeganistão', 'gentilico' => 'afegão(ã)', 'gentilicoM' => 'afegão', 'gentilicoF' => 'afegã', 'codPais' => 'AFG'],
            ['pais' => 'África do Sul', 'gentilico' => 'sul-africano(a)', 'gentilicoM' => 'sul-africano', 'gentilicoF' => 'sul-africana', 'codPais' => 'ZAF'],
            ['pais' => 'Albânia', 'gentilico' => 'albanês(a)', 'gentilicoM' => 'albanês', 'gentilicoF' => 'albanesa', 'codPais' => 'ALB'],
            ['pais' => 'Alemanha', 'gentilico' => 'alemão(ã)', 'gentilicoM' => 'alemão', 'gentilicoF' => 'alemã', 'codPais' => 'DEU'],
            ['pais' => 'Andorra', 'gentilico' => 'andorrano(a)', 'gentilicoM' => 'andorrano', 'gentilicoF' => 'andorrana', 'codPais' => 'AND'],
            ['pais' => 'Angola', 'gentilico' => 'angolano(a)', 'gentilicoM' => 'angolano', 'gentilicoF' => 'angolana', 'codPais' => 'AGO'],
            ['pais' => 'Antígua e Barbuda', 'gentilico' => 'antiguano(a)', 'gentilicoM' => 'antiguano', 'gentilicoF' => 'antiguana', 'codPais' => 'ATG'],
            ['pais' => 'Arábia Saudita', 'gentilico' => 'saudita', 'gentilicoM' => 'saudita', 'gentilicoF' => 'saudita', 'codPais' => 'SAU'],
            ['pais' => 'Argélia', 'gentilico' => 'argelino(a)', 'gentilicoM' => 'argelino', 'gentilicoF' => 'argelina', 'codPais' => 'DZA'],
            ['pais' => 'Argentina', 'gentilico' => 'argentino(a)', 'gentilicoM' => 'argentino', 'gentilicoF' => 'argentina', 'codPais' => 'ARG'],
            ['pais' => 'Armênia', 'gentilico' => 'armênio(a)', 'gentilicoM' => 'armênio', 'gentilicoF' => 'armênia', 'codPais' => 'ARM'],
            ['pais' => 'Austrália', 'gentilico' => 'australiano(a)', 'gentilicoM' => 'australiano', 'gentilicoF' => 'australiana', 'codPais' => 'AUS'],
            ['pais' => 'Áustria', 'gentilico' => 'austríaco(a)', 'gentilicoM' => 'austríaco', 'gentilicoF' => 'austríaca', 'codPais' => 'AUT'],
            ['pais' => 'Azerbaijão', 'gentilico' => 'azerbaijano(a)', 'gentilicoM' => 'azerbaijano', 'gentilicoF' => 'azerbaijana', 'codPais' => 'AZE'],
            ['pais' => 'Bahamas', 'gentilico' => 'bahamense(e)', 'gentilicoM' => 'bahamense', 'gentilicoF' => 'bahamense', 'codPais' => 'BHS'],
            ['pais' => 'Bahrein', 'gentilico' => 'bahrenita', 'gentilicoM' => 'bahrenita', 'gentilicoF' => 'bahrenita', 'codPais' => 'BHR'],
            ['pais' => 'Bangladesh', 'gentilico' => 'bengalês(a)', 'gentilicoM' => 'bengalês', 'gentilicoF' => 'bengalesa', 'codPais' => 'BGD'],
            ['pais' => 'Barbados', 'gentilico' => 'barbadiano(a)', 'gentilicoM' => 'barbadiano', 'gentilicoF' => 'barbadiana', 'codPais' => 'BRB'],
            ['pais' => 'Belarus', 'gentilico' => 'bielorrusso(a)', 'gentilicoM' => 'bielorrusso', 'gentilicoF' => 'bielorrussa', 'codPais' => 'BLR'],
            ['pais' => 'Bélgica', 'gentilico' => 'belga', 'gentilicoM' => 'belga', 'gentilicoF' => 'belga', 'codPais' => 'BEL'],
            ['pais' => 'Belize', 'gentilico' => 'belizenho(a)', 'gentilicoM' => 'belizenho', 'gentilicoF' => 'belizenha', 'codPais' => 'BLZ'],
            ['pais' => 'Benin', 'gentilico' => 'beninense', 'gentilicoM' => 'beninense', 'gentilicoF' => 'beninense', 'codPais' => 'BEN'],
            ['pais' => 'Butão', 'gentilico' => 'butanês(a)', 'gentilicoM' => 'butanês', 'gentilicoF' => 'butanesa', 'codPais' => 'BTN'],
            ['pais' => 'Bolívia', 'gentilico' => 'boliviano(a)', 'gentilicoM' => 'boliviano', 'gentilicoF' => 'boliviana', 'codPais' => 'BOL'],
            ['pais' => 'Bósnia e Herzegovina', 'gentilico' => 'bósnio(a)', 'gentilicoM' => 'bósnio', 'gentilicoF' => 'bósnia', 'codPais' => 'BIH'],
            ['pais' => 'Botsuana', 'gentilico' => 'botsuanense', 'gentilicoM' => 'botsuanense', 'gentilicoF' => 'botsuanense', 'codPais' => 'BWA'],
            ['pais' => 'Brasil', 'gentilico' => 'brasileiro(a)', 'gentilicoM' => 'brasileiro', 'gentilicoF' => 'brasileira', 'codPais' => 'BRA', 'destaque' => true],
            ['pais' => 'Brunei', 'gentilico' => 'bruneano(a)', 'gentilicoM' => 'bruneano', 'gentilicoF' => 'bruneana', 'codPais' => 'BRN'],
            ['pais' => 'Bulgária', 'gentilico' => 'búlgaro(a)', 'gentilicoM' => 'búlgaro', 'gentilicoF' => 'búlgara', 'codPais' => 'BGR'],
            ['pais' => 'Burkina Faso', 'gentilico' => 'burquinense', 'gentilicoM' => 'burquinense', 'gentilicoF' => 'burquinense', 'codPais' => 'BFA'],
            ['pais' => 'Burundi', 'gentilico' => 'burundinês(a)', 'gentilicoM' => 'burundinês', 'gentilicoF' => 'burundinesa', 'codPais' => 'BDI'],
            ['pais' => 'Cabo Verde', 'gentilico' => 'cabo-verdiano(a)', 'gentilicoM' => 'cabo-verdiano', 'gentilicoF' => 'cabo-verdiana', 'codPais' => 'CPV'],
            ['pais' => 'Camarões', 'gentilico' => 'camaronês(a)', 'gentilicoM' => 'camaronês', 'gentilicoF' => 'camaronesa', 'codPais' => 'CMR'],
            ['pais' => 'Canadá', 'gentilico' => 'canadense', 'gentilicoM' => 'canadense', 'gentilicoF' => 'canadense', 'codPais' => 'CAN'],
            ['pais' => 'Catar', 'gentilico' => 'catarense', 'gentilicoM' => 'catarense', 'gentilicoF' => 'catarense', 'codPais' => 'QAT'],
            ['pais' => 'Cazaquistão', 'gentilico' => 'cazaque', 'gentilicoM' => 'cazaque', 'gentilicoF' => 'cazaque', 'codPais' => 'KAZ'],
            ['pais' => 'Chade', 'gentilico' => 'chadiano(a)', 'gentilicoM' => 'chadiano', 'gentilicoF' => 'chadiana', 'codPais' => 'TCD'],
            ['pais' => 'Chile', 'gentilico' => 'chileno(a)', 'gentilicoM' => 'chileno', 'gentilicoF' => 'chilena', 'codPais' => 'CHL'],
            ['pais' => 'China', 'gentilico' => 'chinês', 'gentilicoM' => 'chinês', 'gentilicoF' => 'chinesa', 'codPais' => 'CHN'],
            ['pais' => 'Chipre', 'gentilico' => 'cipriota', 'gentilicoM' => 'cipriota', 'gentilicoF' => 'cipriota', 'codPais' => 'CYP'],
            ['pais' => 'Colômbia', 'gentilico' => 'colombiano(a)', 'gentilicoM' => 'colombiano', 'gentilicoF' => 'colombiana', 'codPais' => 'COL'],
            ['pais' => 'Comores', 'gentilico' => 'comorense', 'gentilicoM' => 'comorense', 'gentilicoF' => 'comorense', 'codPais' => 'COM'],
            ['pais' => 'Congo', 'gentilico' => 'congolês(a)', 'gentilicoM' => 'congolês', 'gentilicoF' => 'congolesa', 'codPais' => 'COG'],
            ['pais' => 'Coreia do Norte', 'gentilico' => 'norte-coreano(a)', 'gentilicoM' => 'norte-coreano', 'gentilicoF' => 'norte-coreana', 'codPais' => 'PRK'],
            ['pais' => 'Coreia do Sul', 'gentilico' => 'sul-coreano(a)', 'gentilicoM' => 'sul-coreano', 'gentilicoF' => 'sul-coreana', 'codPais' => 'KOR'],
            ['pais' => 'Costa do Marfim', 'gentilico' => 'marfinense', 'gentilicoM' => 'marfinense', 'gentilicoF' => 'marfinense', 'codPais' => 'CIV'],
            ['pais' => 'Costa Rica', 'gentilico' => 'costarriquenho(a)', 'gentilicoM' => 'costarriquenho', 'gentilicoF' => 'costarriquenha', 'codPais' => 'CRI'],
            ['pais' => 'Croácia', 'gentilico' => 'croata', 'gentilicoM' => 'croata', 'gentilicoF' => 'croata', 'codPais' => 'HRV'],
            ['pais' => 'Cuba', 'gentilico' => 'cubano(a)', 'gentilicoM' => 'cubano', 'gentilicoF' => 'cubana', 'codPais' => 'CUB'],
            ['pais' => 'Dinamarca', 'gentilico' => 'dinamarquês(a)', 'gentilicoM' => 'dinamarquês', 'gentilicoF' => 'dinamarquesa', 'codPais' => 'DNK'],
            ['pais' => 'Djibuti', 'gentilico' => 'djibutiano(a)', 'gentilicoM' => 'djibutiano', 'gentilicoF' => 'djibutiana', 'codPais' => 'DJI'],
            ['pais' => 'Dominica', 'gentilico' => 'dominiquense', 'gentilicoM' => 'dominiquense', 'gentilicoF' => 'dominiquense', 'codPais' => 'DMA'],
            ['pais' => 'Egito', 'gentilico' => 'egípcio(a)', 'gentilicoM' => 'egípcio', 'gentilicoF' => 'egípcia', 'codPais' => 'EGY'],
            ['pais' => 'El Salvador', 'gentilico' => 'salvadorenho(a)', 'gentilicoM' => 'salvadorenho', 'gentilicoF' => 'salvadorenha', 'codPais' => 'SLV'],
            ['pais' => 'Emirados Árabes Unidos', 'gentilico' => 'emiradense', 'gentilicoM' => 'emiradense', 'gentilicoF' => 'emiradense', 'codPais' => 'ARE'],
            ['pais' => 'Equador', 'gentilico' => 'equatoriano(a)', 'gentilicoM' => 'equatoriano', 'gentilicoF' => 'equatoriana', 'codPais' => 'ECU'],
            ['pais' => 'Eritreia', 'gentilico' => 'eritreu(a)', 'gentilicoM' => 'eritreu', 'gentilicoF' => 'eritreia', 'codPais' => 'ERI'],
            ['pais' => 'Eslováquia', 'gentilico' => 'eslovaco(a)', 'gentilicoM' => 'eslovaco', 'gentilicoF' => 'eslovaca', 'codPais' => 'SVK'],
            ['pais' => 'Eslovênia', 'gentilico' => 'esloveno(a)', 'gentilicoM' => 'esloveno', 'gentilicoF' => 'eslovena', 'codPais' => 'SVN'],
            ['pais' => 'Espanha', 'gentilico' => 'espanhol(a)', 'gentilicoM' => 'espanhol', 'gentilicoF' => 'espanhola', 'codPais' => 'ESP'],
            ['pais' => 'Estados Unidos', 'gentilico' => 'norte-americano(a)', 'gentilicoM' => 'norte-americano', 'gentilicoF' => 'norte-americana', 'codPais' => 'USA'],
            ['pais' => 'Estônia', 'gentilico' => 'estoniano(a)', 'gentilicoM' => 'estoniano', 'gentilicoF' => 'estoniana', 'codPais' => 'EST'],
            ['pais' => 'Etiópia', 'gentilico' => 'etíope', 'gentilicoM' => 'etíope', 'gentilicoF' => 'etíope', 'codPais' => 'ETH'],
            ['pais' => 'Fiji', 'gentilico' => 'fijiano(a)', 'gentilicoM' => 'fijiano', 'gentilicoF' => 'fijiana', 'codPais' => 'FJI'],
            ['pais' => 'Filipinas', 'gentilico' => 'filipino(a)', 'gentilicoM' => 'filipino', 'gentilicoF' => 'filipina', 'codPais' => 'PHL'],
            ['pais' => 'Finlândia', 'gentilico' => 'finlandês(a)', 'gentilicoM' => 'finlandês', 'gentilicoF' => 'finlandesa', 'codPais' => 'FIN'],
            ['pais' => 'França', 'gentilico' => 'francês(a)', 'gentilicoM' => 'francês', 'gentilicoF' => 'francesa', 'codPais' => 'FRA'],
            ['pais' => 'Gabão', 'gentilico' => 'gabonense(e)', 'gentilicoM' => 'gabonense', 'gentilicoF' => 'gabonense', 'codPais' => 'GAB'],
            ['pais' => 'Gâmbia', 'gentilico' => 'gambiano(a)', 'gentilicoM' => 'gambiano', 'gentilicoF' => 'gambiana', 'codPais' => 'GMB'],
            ['pais' => 'Gana', 'gentilico' => 'ganense', 'gentilicoM' => 'ganense', 'gentilicoF' => 'ganense', 'codPais' => 'GHA'],
            ['pais' => 'Geórgia', 'gentilico' => 'georgiano(a)', 'gentilicoM' => 'georgiano', 'gentilicoF' => 'georgiana', 'codPais' => 'GEO'],
            ['pais' => 'Grécia', 'gentilico' => 'grego(a)', 'gentilicoM' => 'grego', 'gentilicoF' => 'grega', 'codPais' => 'GRC'],
            ['pais' => 'Granada', 'gentilico' => 'granadino(a)', 'gentilicoM' => 'granadino', 'gentilicoF' => 'granadina', 'codPais' => 'GRD'],
            ['pais' => 'Guatemala', 'gentilico' => 'guatemalteco(a)', 'gentilicoM' => 'guatemalteco', 'gentilicoF' => 'guatemalteca', 'codPais' => 'GTM'],
            ['pais' => 'Guiana', 'gentilico' => 'guianense', 'gentilicoM' => 'guianense', 'gentilicoF' => 'guianense', 'codPais' => 'GUY'],
            ['pais' => 'Guiné', 'gentilico' => 'guineense', 'gentilicoM' => 'guineense', 'gentilicoF' => 'guineense', 'codPais' => 'GIN'],
            ['pais' => 'Guiné Equatorial', 'gentilico' => 'equato-guineense', 'gentilicoM' => 'equato-guineense', 'gentilicoF' => 'equato-guineense', 'codPais' => 'GNQ'],
            ['pais' => 'Guiné-Bissau', 'gentilico' => 'guineense', 'gentilicoM' => 'guineense', 'gentilicoF' => 'guineense', 'codPais' => 'GNB'],
            ['pais' => 'Haiti', 'gentilico' => 'haitiano(a)', 'gentilicoM' => 'haitiano', 'gentilicoF' => 'haitiana', 'codPais' => 'HTI'],
            ['pais' => 'Honduras', 'gentilico' => 'hondurenho(a)', 'gentilicoM' => 'hondurenho', 'gentilicoF' => 'hondurenha', 'codPais' => 'HND'],
            ['pais' => 'Hungria', 'gentilico' => 'húngaro(a)', 'gentilicoM' => 'húngaro', 'gentilicoF' => 'húngara', 'codPais' => 'HUN'],
            ['pais' => 'Iémen', 'gentilico' => 'iemenita(a)', 'gentilicoM' => 'iemenita', 'gentilicoF' => 'iemenita', 'codPais' => 'YEM'],
            ['pais' => 'Ilhas Marshall', 'gentilico' => 'marshalês(a)', 'gentilicoM' => 'marshalês', 'gentilicoF' => 'marshalesa', 'codPais' => 'MHL'],
            ['pais' => 'Índia', 'gentilico' => 'indiano(a)', 'gentilicoM' => 'indiano', 'gentilicoF' => 'indiana', 'codPais' => 'IND'],
            ['pais' => 'Indonésia', 'gentilico' => 'indonésio(a)', 'gentilicoM' => 'indonésio', 'gentilicoF' => 'indonésia', 'codPais' => 'IDN'],
            ['pais' => 'Irã', 'gentilico' => 'iraniano(a)', 'gentilicoM' => 'iraniano', 'gentilicoF' => 'iraniana', 'codPais' => 'IRN'],
            ['pais' => 'Iraque', 'gentilico' => 'iraquiano(a)', 'gentilicoM' => 'iraquiano', 'gentilicoF' => 'iraquiana', 'codPais' => 'IRQ'],
            ['pais' => 'Irlanda', 'gentilico' => 'irlandês(a)', 'gentilicoM' => 'irlandês', 'gentilicoF' => 'irlandesa', 'codPais' => 'IRL'],
            ['pais' => 'Islândia', 'gentilico' => 'islandês(a)', 'gentilicoM' => 'islandês', 'gentilicoF' => 'islandesa', 'codPais' => 'ISL'],
            ['pais' => 'Israel', 'gentilico' => 'israelense', 'gentilicoM' => 'israelense', 'gentilicoF' => 'israelense', 'codPais' => 'ISR'],
            ['pais' => 'Itália', 'gentilico' => 'italiano(a)', 'gentilicoM' => 'italiano', 'gentilicoF' => 'italiana', 'codPais' => 'ITA'],
            ['pais' => 'Jamaica', 'gentilico' => 'jamaicano(a)', 'gentilicoM' => 'jamaicano', 'gentilicoF' => 'jamaicana', 'codPais' => 'JAM'],
            ['pais' => 'Japão', 'gentilico' => 'japonês(a)', 'gentilicoM' => 'japonês', 'gentilicoF' => 'japonesa', 'codPais' => 'JPN', 'destaque' => true],
            ['pais' => 'Jordânia', 'gentilico' => 'jordaniano(a)', 'gentilicoM' => 'jordaniano', 'gentilicoF' => 'jordaniana', 'codPais' => 'JOR'],
            ['pais' => 'Kiribati', 'gentilico' => 'kiribatiano(a)', 'gentilicoM' => 'kiribatiano', 'gentilicoF' => 'kiribatiana', 'codPais' => 'KIR'],
            ['pais' => 'Kosovo', 'gentilico' => 'kosovar', 'gentilicoM' => 'kosovar', 'gentilicoF' => 'kosovar', 'codPais' => 'XXK'],
            ['pais' => 'Kuwait', 'gentilico' => 'kuwaitiano(a)', 'gentilicoM' => 'kuwaitiano', 'gentilicoF' => 'kuwaitiana', 'codPais' => 'KWT'],
            ['pais' => 'Laos', 'gentilico' => 'laosiano(a)', 'gentilicoM' => 'laosiano', 'gentilicoF' => 'laosiana', 'codPais' => 'LAO'],
            ['pais' => 'Lesoto', 'gentilico' => 'lesotiano(a)', 'gentilicoM' => 'lesotiano', 'gentilicoF' => 'lesotiana', 'codPais' => 'LSO'],
            ['pais' => 'Letônia', 'gentilico' => 'letão(ã)', 'gentilicoM' => 'letão', 'gentilicoF' => 'letã', 'codPais' => 'LVA'],
            ['pais' => 'Líbano', 'gentilico' => 'libanês(a)', 'gentilicoM' => 'libanês', 'gentilicoF' => 'libanesa', 'codPais' => 'LBN'],
            ['pais' => 'Libéria', 'gentilico' => 'liberiano(a)', 'gentilicoM' => 'liberiano', 'gentilicoF' => 'liberiana', 'codPais' => 'LBR'],
            ['pais' => 'Líbia', 'gentilico' => 'líbio(a)', 'gentilicoM' => 'líbio', 'gentilicoF' => 'líbia', 'codPais' => 'LBY'],
            ['pais' => 'Liechtenstein', 'gentilico' => 'liechtensteinense', 'gentilicoM' => 'liechtensteinense', 'gentilicoF' => 'liechtensteinense', 'codPais' => 'LIE'],
            ['pais' => 'Lituânia', 'gentilico' => 'lituano(a)', 'gentilicoM' => 'lituano', 'gentilicoF' => 'lituana', 'codPais' => 'LTU'],
            ['pais' => 'Luxemburgo', 'gentilico' => 'luxemburguês(a)', 'gentilicoM' => 'luxemburguês', 'gentilicoF' => 'luxemburguesa', 'codPais' => 'LUX'],
            ['pais' => 'Macedônia do Norte', 'gentilico' => 'macedônio(a)', 'gentilicoM' => 'macedônio', 'gentilicoF' => 'macedônia', 'codPais' => 'MKD'],
            ['pais' => 'Madagascar', 'gentilico' => 'madagascarense', 'gentilicoM' => 'madagascarense', 'gentilicoF' => 'madagascarense', 'codPais' => 'MDG'],
            ['pais' => 'Malásia', 'gentilico' => 'malaio(a)', 'gentilicoM' => 'malaio', 'gentilicoF' => 'malaia', 'codPais' => 'MYS'],
            ['pais' => 'Malawi', 'gentilico' => 'malauiano(a)', 'gentilicoM' => 'malauiano', 'gentilicoF' => 'malauiana', 'codPais' => 'MWI'],
            ['pais' => 'Maldivas', 'gentilico' => 'maldivo(a)', 'gentilicoM' => 'maldivo', 'gentilicoF' => 'maldiva', 'codPais' => 'MDV'],
            ['pais' => 'Mali', 'gentilico' => 'malinês(a)', 'gentilicoM' => 'malinês', 'gentilicoF' => 'malinesa', 'codPais' => 'MLI'],
            ['pais' => 'Malta', 'gentilico' => 'maltês(a)', 'gentilicoM' => 'maltês', 'gentilicoF' => 'maltesa', 'codPais' => 'MLT'],
            ['pais' => 'Marrocos', 'gentilico' => 'marroquino(a)', 'gentilicoM' => 'marroquino', 'gentilicoF' => 'marroquina', 'codPais' => 'MAR'],
            ['pais' => 'Maurícia', 'gentilico' => 'mauriciano(a)', 'gentilicoM' => 'mauriciano', 'gentilicoF' => 'mauriciana', 'codPais' => 'MUS'],
            ['pais' => 'Mauritânia', 'gentilico' => 'mauritano(a)', 'gentilicoM' => 'mauritano', 'gentilicoF' => 'mauritana', 'codPais' => 'MRT'],
            ['pais' => 'México', 'gentilico' => 'mexicano(a)', 'gentilicoM' => 'mexicano', 'gentilicoF' => 'mexicana', 'codPais' => 'MEX'],
            ['pais' => 'Micronésia', 'gentilico' => 'micronésio(a)', 'gentilicoM' => 'micronésio', 'gentilicoF' => 'micronésia', 'codPais' => 'FSM'],
            ['pais' => 'Moçambique', 'gentilico' => 'moçambicano(a)', 'gentilicoM' => 'moçambicano', 'gentilicoF' => 'moçambicana', 'codPais' => 'MOZ'],
            ['pais' => 'Moldávia', 'gentilico' => 'moldávio(a)', 'gentilicoM' => 'moldávio', 'gentilicoF' => 'moldávia', 'codPais' => 'MDA'],
            ['pais' => 'Mônaco', 'gentilico' => 'monegasco(a)', 'gentilicoM' => 'monegasco', 'gentilicoF' => 'monegasca', 'codPais' => 'MCO'],
            ['pais' => 'Mongólia', 'gentilico' => 'mongol', 'gentilicoM' => 'mongol', 'gentilicoF' => 'mongol', 'codPais' => 'MNG'],
            ['pais' => 'Montenegro', 'gentilico' => 'montenegrino(a)', 'gentilicoM' => 'montenegrino', 'gentilicoF' => 'montenegrina', 'codPais' => 'MNE'],
            ['pais' => 'Myanmar', 'gentilico' => 'birmanês(a)', 'gentilicoM' => 'birmanês', 'gentilicoF' => 'birmaneza', 'codPais' => 'MMR'],
            ['pais' => 'Namíbia', 'gentilico' => 'namibiano(a)', 'gentilicoM' => 'namibiano', 'gentilicoF' => 'namibiana', 'codPais' => 'NAM'],
            ['pais' => 'Nauru', 'gentilico' => 'nauruano(a)', 'gentilicoM' => 'nauruano', 'gentilicoF' => 'nauruana', 'codPais' => 'NRU'],
            ['pais' => 'Nepal', 'gentilico' => 'nepalês(a)', 'gentilicoM' => 'nepalês', 'gentilicoF' => 'nepalesa', 'codPais' => 'NPL'],
            ['pais' => 'Nicarágua', 'gentilico' => 'nicaraguense', 'gentilicoM' => 'nicaraguense', 'gentilicoF' => 'nicaraguense', 'codPais' => 'NIC'],
            ['pais' => 'Níger', 'gentilico' => 'nigerino(a)', 'gentilicoM' => 'nigerino', 'gentilicoF' => 'nigerina', 'codPais' => 'NER'],
            ['pais' => 'Nigéria', 'gentilico' => 'nigeriano(a)', 'gentilicoM' => 'nigeriano', 'gentilicoF' => 'nigeriana', 'codPais' => 'NGA'],
            ['pais' => 'Noruega', 'gentilico' => 'norueguês(a)', 'gentilicoM' => 'norueguês', 'gentilicoF' => 'norueguesa', 'codPais' => 'NOR'],
            ['pais' => 'Nova Zelândia', 'gentilico' => 'neozelandês(a)', 'gentilicoM' => 'neozelandês', 'gentilicoF' => 'neozelandesa', 'codPais' => 'NZL'],
            ['pais' => 'Omã', 'gentilico' => 'omanense', 'gentilicoM' => 'omanense', 'gentilicoF' => 'omanense', 'codPais' => 'OMN'],
            ['pais' => 'Países Baixos', 'gentilico' => 'holandês(a)', 'gentilicoM' => 'holandês', 'gentilicoF' => 'holandesa', 'codPais' => 'NLD'],
            ['pais' => 'Palau', 'gentilico' => 'palauano(a)', 'gentilicoM' => 'palauano', 'gentilicoF' => 'palauana', 'codPais' => 'PLW'],
            ['pais' => 'Panamá', 'gentilico' => 'panamenho(a)', 'gentilicoM' => 'panamenho', 'gentilicoF' => 'panamenha', 'codPais' => 'PAN'],
            ['pais' => 'Papua-Nova Guiné', 'gentilico' => 'papua', 'gentilicoM' => 'papua', 'gentilicoF' => 'papua', 'codPais' => 'PNG'],
            ['pais' => 'Paquistão', 'gentilico' => 'paquistanês(a)', 'gentilicoM' => 'paquistanês', 'gentilicoF' => 'paquistanesa', 'codPais' => 'PAK'],
            ['pais' => 'Paraguai', 'gentilico' => 'paraguaio(a)', 'gentilicoM' => 'paraguaio', 'gentilicoF' => 'paraguaia', 'codPais' => 'PRY'],
            ['pais' => 'Peru', 'gentilico' => 'peruano(a)', 'gentilicoM' => 'peruano', 'gentilicoF' => 'peruana', 'codPais' => 'PER'],
            ['pais' => 'Polônia', 'gentilico' => 'polonês(a)', 'gentilicoM' => 'polonês', 'gentilicoF' => 'polonesa', 'codPais' => 'POL'],
            ['pais' => 'Portugal', 'gentilico' => 'português(a)', 'gentilicoM' => 'português', 'gentilicoF' => 'portuguesa', 'codPais' => 'PRT'],
            ['pais' => 'Quênia', 'gentilico' => 'queniano(a)', 'gentilicoM' => 'queniano', 'gentilicoF' => 'queniana', 'codPais' => 'KEN'],
            ['pais' => 'Quirguistão', 'gentilico' => 'quirguiz', 'gentilicoM' => 'quirguiz', 'gentilicoF' => 'quirguiz', 'codPais' => 'KGZ'],
            ['pais' => 'Reino Unido', 'gentilico' => 'britânico(a)', 'gentilicoM' => 'britânico', 'gentilicoF' => 'britânica', 'codPais' => 'GBR'],
            ['pais' => 'República Centro-Africana', 'gentilico' => 'centro-africano(a)', 'gentilicoM' => 'centro-africano', 'gentilicoF' => 'centro-africana', 'codPais' => 'CAF'],
            ['pais' => 'República Democrática do Congo', 'gentilico' => 'congolês(a)', 'gentilicoM' => 'congolês', 'gentilicoF' => 'congolesa', 'codPais' => 'COD'],
            ['pais' => 'República Dominicana', 'gentilico' => 'dominicano(a)', 'gentilicoM' => 'dominicano', 'gentilicoF' => 'dominicana', 'codPais' => 'DOM'],
            ['pais' => 'Romênia', 'gentilico' => 'romeno(a)', 'gentilicoM' => 'romeno', 'gentilicoF' => 'romena', 'codPais' => 'ROU'],
            ['pais' => 'Ruanda', 'gentilico' => 'ruandês(a)', 'gentilicoM' => 'ruandês', 'gentilicoF' => 'ruandesa', 'codPais' => 'RWA'],
            ['pais' => 'Rússia', 'gentilico' => 'russo(a)', 'gentilicoM' => 'russo', 'gentilicoF' => 'russa', 'codPais' => 'RUS'],
            ['pais' => 'Salomão', 'gentilico' => 'salomônico(a)', 'gentilicoM' => 'salomônico', 'gentilicoF' => 'salomônica', 'codPais' => 'SLB'],
            ['pais' => 'Samoa', 'gentilico' => 'samoano(a)', 'gentilicoM' => 'samoano', 'gentilicoF' => 'samoana', 'codPais' => 'WSM'],
            ['pais' => 'Santa Lúcia', 'gentilico' => 'santa-lucense', 'gentilicoM' => 'santa-lucense', 'gentilicoF' => 'santa-lucense', 'codPais' => 'LCA'],
            ['pais' => 'São Cristóvão e Névis', 'gentilico' => 'são-cristovense', 'gentilicoM' => 'são-cristovense', 'gentilicoF' => 'são-cristovense', 'codPais' => 'KNA'],
            ['pais' => 'São Tomé e Príncipe', 'gentilico' => 'são-tomense', 'gentilicoM' => 'são-tomense', 'gentilicoF' => 'são-tomense', 'codPais' => 'STP'],
            ['pais' => 'São Vicente e Granadinas', 'gentilico' => 'são-vicentino(a)', 'gentilicoM' => 'são-vicentino', 'gentilicoF' => 'são-vicentina', 'codPais' => 'VCT'],
            ['pais' => 'Senegal', 'gentilico' => 'senegalês(a)', 'gentilicoM' => 'senegalês', 'gentilicoF' => 'senegalesa', 'codPais' => 'SEN'],
            ['pais' => 'Serra Leoa', 'gentilico' => 'serra-leonês(a)', 'gentilicoM' => 'serra-leonês', 'gentilicoF' => 'serra-leonesa', 'codPais' => 'SLE'],
            ['pais' => 'Seychelles', 'gentilico' => 'seichelense', 'gentilicoM' => 'seichelense', 'gentilicoF' => 'seichelense', 'codPais' => 'SYC'],
            ['pais' => 'Singapura', 'gentilico' => 'singapurense', 'gentilicoM' => 'singapurense', 'gentilicoF' => 'singapurense', 'codPais' => 'SGP'],
            ['pais' => 'Síria', 'gentilico' => 'sírio(a)', 'gentilicoM' => 'sírio', 'gentilicoF' => 'síria', 'codPais' => 'SYR'],
            ['pais' => 'Somália', 'gentilico' => 'somali', 'gentilicoM' => 'somali', 'gentilicoF' => 'somali', 'codPais' => 'SOM'],
            ['pais' => 'Sri Lanka', 'gentilico' => 'cingalês(a)', 'gentilicoM' => 'cingalês', 'gentilicoF' => 'cingalesa', 'codPais' => 'LKA'],
            ['pais' => 'Suazilândia', 'gentilico' => 'suazi', 'gentilicoM' => 'suazi', 'gentilicoF' => 'suazi', 'codPais' => 'SWZ'],
            ['pais' => 'Sudão', 'gentilico' => 'sudanês(a)', 'gentilicoM' => 'sudanês', 'gentilicoF' => 'sudanesa', 'codPais' => 'SDN'],
            ['pais' => 'Sudão do Sul', 'gentilico' => 'sul-sudanês(a)', 'gentilicoM' => 'sul-sudanês', 'gentilicoF' => 'sul-sudanesa', 'codPais' => 'SSD'],
            ['pais' => 'Suécia', 'gentilico' => 'sueco(a)', 'gentilicoM' => 'sueco', 'gentilicoF' => 'sueca', 'codPais' => 'SWE'],
            ['pais' => 'Suíça', 'gentilico' => 'suíço(a)', 'gentilicoM' => 'suíço', 'gentilicoF' => 'suíça', 'codPais' => 'CHE'],
            ['pais' => 'Suriname', 'gentilico' => 'surinamês(a)', 'gentilicoM' => 'surinamês', 'gentilicoF' => 'surinamesa', 'codPais' => 'SUR'],
            ['pais' => 'Tailândia', 'gentilico' => 'tailandês(a)', 'gentilicoM' => 'tailandês', 'gentilicoF' => 'tailandesa', 'codPais' => 'THA'],
            ['pais' => 'Tajiquistão', 'gentilico' => 'tadjique', 'gentilicoM' => 'tadjique', 'gentilicoF' => 'tadjique', 'codPais' => 'TJK'],
            ['pais' => 'Tanzânia', 'gentilico' => 'tanzaniano(a)', 'gentilicoM' => 'tanzaniano', 'gentilicoF' => 'tanzaniana', 'codPais' => 'TZA'],
            ['pais' => 'Timor-Leste', 'gentilico' => 'timorense', 'gentilicoM' => 'timorense', 'gentilicoF' => 'timorense', 'codPais' => 'TLS'],
            ['pais' => 'Togo', 'gentilico' => 'togolês(a)', 'gentilicoM' => 'togolês', 'gentilicoF' => 'togolesa', 'codPais' => 'TGO'],
            ['pais' => 'Tonga', 'gentilico' => 'tonganês(a)', 'gentilicoM' => 'tonganês', 'gentilicoF' => 'tongana', 'codPais' => 'TON'],
            ['pais' => 'Trinidad e Tobago', 'gentilico' => 'trinitário(a)', 'gentilicoM' => 'trinitário', 'gentilicoF' => 'trinitária', 'codPais' => 'TTO'],
            ['pais' => 'Tunísia', 'gentilico' => 'tunisiano(a)', 'gentilicoM' => 'tunisiano', 'gentilicoF' => 'tunisiana', 'codPais' => 'TUN'],
            ['pais' => 'Turcomenistão', 'gentilico' => 'turcomeno(a)', 'gentilicoM' => 'turcomeno', 'gentilicoF' => 'turcomena', 'codPais' => 'TKM'],
            ['pais' => 'Turquia', 'gentilico' => 'turco(a)', 'gentilicoM' => 'turco', 'gentilicoF' => 'turca', 'codPais' => 'TUR'],
            ['pais' => 'Tuvalu', 'gentilico' => 'tuvaluano(a)', 'gentilicoM' => 'tuvaluano', 'gentilicoF' => 'tuvaluana', 'codPais' => 'TUV'],
            ['pais' => 'Ucrânia', 'gentilico' => 'ucraniano(a)', 'gentilicoM' => 'ucraniano', 'gentilicoF' => 'ucraniana', 'codPais' => 'UKR'],
            ['pais' => 'Uganda', 'gentilico' => 'ugandense(e)', 'gentilicoM' => 'ugandense', 'gentilicoF' => 'ugandense', 'codPais' => 'UGA'],
            ['pais' => 'Uruguai', 'gentilico' => 'uruguaio(a)', 'gentilicoM' => 'uruguaio', 'gentilicoF' => 'uruguaia', 'codPais' => 'URY'],
            ['pais' => 'Uzbequistão', 'gentilico' => 'uzbeque', 'gentilicoM' => 'uzbeque', 'gentilicoF' => 'uzbeque', 'codPais' => 'UZB'],
            ['pais' => 'Vanuatu', 'gentilico' => 'vanuatuense', 'gentilicoM' => 'vanuatuense', 'gentilicoF' => 'vanuatuense', 'codPais' => 'VUT'],
            ['pais' => 'Vaticano', 'gentilico' => 'vaticano(a)', 'gentilicoM' => 'vaticano', 'gentilicoF' => 'vaticana', 'codPais' => 'VAT'],
            ['pais' => 'Venezuela', 'gentilico' => 'venezuelano(a)', 'gentilicoM' => 'venezuelano', 'gentilicoF' => 'venezuelana', 'codPais' => 'VEN'],
            ['pais' => 'Vietnã', 'gentilico' => 'vietnamita', 'gentilicoM' => 'vietnamita', 'gentilicoF' => 'vietnamita', 'codPais' => 'VNM'],
            ['pais' => 'Zâmbia', 'gentilico' => 'zambiano(a)', 'gentilicoM' => 'zambiano', 'gentilicoF' => 'zambiana', 'codPais' => 'ZMB'],
            ['pais' => 'Zimbábue', 'gentilico' => 'zimbabuano(a)', 'gentilicoM' => 'zimbabuano', 'gentilicoF' => 'zimbabuana', 'codPais' => 'ZWE']
        ];

        foreach ($countries as $county) {
            Country::create($county);
        }
    }
}
