<?php

namespace Database\Seeders;

use App\Models\Occupation;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OccupationSeeder extends Seeder
{
    public function run(): void
    {
        $profissoes = [
            ['profissao' => 'Auxiliar Administrativo(a)', 'profissaoM' => 'Auxiliar Administrativo', 'profissaoF' => 'Auxiliar Administrativa'],
            ['profissao' => 'Auxiliar de Apoio', 'profissaoM' => 'Auxiliar de Apoio', 'profissaoF' => 'Auxiliar de Apoio'],
            ['profissao' => 'Assistente de Chancelaria', 'profissaoM' => 'Assistente de Chancelaria', 'profissaoF' => 'Assistente de Chancelaria'],
            ['profissao' => 'Oficial de Chancelaria', 'profissaoM' => 'Oficial de Chancelaria', 'profissaoF' => 'Oficial de Chancelaria'],
            ['profissao' => 'Diplomata', 'profissaoM' => 'Diplomata', 'profissaoF' => 'Diplomata'],
            ['profissao' => 'Operário(a)', 'profissaoM' => 'Operário', 'profissaoF' => 'Operária'],
            ['profissao' => 'Inspetor(a) de Qualidade', 'profissaoM' => 'Inspetor de Qualidade', 'profissaoF' => 'Inspetora de Qualidade'],
            ['profissao' => 'Cabeleireiro(a)', 'profissaoM' => 'Cabeleireiro', 'profissaoF' => 'Cabeleireira'],
            ['profissao' => 'Manicure', 'profissaoM' => 'Manicure', 'profissaoF' => 'Manicure'],
            ['profissao' => 'Motorista', 'profissaoM' => 'Motorista', 'profissaoF' => 'Motorista'],
            ['profissao' => 'Arquiteto(a)', 'profissaoM' => 'Arquiteto', 'profissaoF' => 'Arquiteta'],
            ['profissao' => 'Médico(a)', 'profissaoM' => 'Médico', 'profissaoF' => 'Médica'],
            ['profissao' => 'Engenheiro(a)', 'profissaoM' => 'Engenheiro', 'profissaoF' => 'Engenheira'],
            ['profissao' => 'Advogado(a)', 'profissaoM' => 'Advogado', 'profissaoF' => 'Advogada'],
            ['profissao' => 'Doméstico(a)', 'profissaoM' => 'Doméstico', 'profissaoF' => 'Doméstica'],
            ['profissao' => 'Diarista', 'profissaoM' => 'Diarista', 'profissaoF' => 'Diarista'],
            ['profissao' => 'Serralheiro(a)', 'profissaoM' => 'Serralheiro', 'profissaoF' => 'Serralheira'],
            ['profissao' => 'Promotor(a) de Eventos', 'profissaoM' => 'Promotor de Eventos', 'profissaoF' => 'Promotora de Eventos'],
            ['profissao' => 'Influenciador(a)', 'profissaoM' => 'Influenciador', 'profissaoF' => 'Influenciadora'],
            ['profissao' => 'Empilhador(a)', 'profissaoM' => 'Empilhador', 'profissaoF' => 'Empilhadora'],
            ['profissao' => 'Soldador(a)', 'profissaoM' => 'Soldador', 'profissaoF' => 'Soldadora'],
            ['profissao' => 'Segurança', 'profissaoM' => 'Segurança', 'profissaoF' => 'Segurança'],
            ['profissao' => 'Enfermeiro(a)', 'profissaoM' => 'Enfermeiro', 'profissaoF' => 'Enfermeira'],
            ['profissao' => 'Professor(a)', 'profissaoM' => 'Professor', 'profissaoF' => 'Professora'],
            ['profissao' => 'Empresário(a)', 'profissaoM' => 'Empresário', 'profissaoF' => 'Empresária'],
            ['profissao' => 'Cozinheiro(a)', 'profissaoM' => 'Cozinheiro', 'profissaoF' => 'Cozinheira'],
            ['profissao' => 'Estudante', 'profissaoM' => 'Estudante', 'profissaoF' => 'Estudante'],
            ['profissao' => 'Contabilista', 'profissaoM' => 'Contabilista', 'profissaoF' => 'Contabilista'],
            ['profissao' => 'Atendente', 'profissaoM' => 'Atendente', 'profissaoF' => 'Atendente'],
            ['profissao' => 'Programador(a)', 'profissaoM' => 'Programador', 'profissaoF' => 'Programadora'],
            ['profissao' => 'Ferroviário(a)', 'profissaoM' => 'Ferroviário', 'profissaoF' => 'Ferroviária'],
            ['profissao' => 'Aeroviário(a)', 'profissaoM' => 'Aeroviário', 'profissaoF' => 'Aeroviária'],
            ['profissao' => 'Entregador(a)', 'profissaoM' => 'Entregador', 'profissaoF' => 'Entregadora'],
            ['profissao' => 'Taxista', 'profissaoM' => 'Taxista', 'profissaoF' => 'Taxista'],
            ['profissao' => 'Tradutor(a)', 'profissaoM' => 'Tradutor', 'profissaoF' => 'Tradutora'],
            ['profissao' => 'Interprete', 'profissaoM' => 'Interprete', 'profissaoF' => 'Interprete'],
            ['profissao' => 'Eletricista', 'profissaoM' => 'Eletricista', 'profissaoF' => 'Eletricista'],
            ['profissao' => 'Encanador(a)', 'profissaoM' => 'Encanador', 'profissaoF' => 'Encanadora'],
            ['profissao' => 'Construtor(a) Civil', 'profissaoM' => 'Construtor Civil', 'profissaoF' => 'Construtora Civil'],
            ['profissao' => 'Encarregado', 'profissaoM' => 'Encarregado', 'profissaoF' => 'Encarregado'],
            ['profissao' => 'Autônomo(a)', 'profissaoM' => 'Autônomo', 'profissaoF' => 'Autônoma'],
            ['profissao' => 'Açougueiro(a)', 'profissaoM' => 'Açougueiro', 'profissaoF' => 'Açougueira'],
            ['profissao' => 'Padeiro(a)', 'profissaoM' => 'Padeiro', 'profissaoF' => 'Padeira'],
            ['profissao' => 'Despachante', 'profissaoM' => 'Despachante', 'profissaoF' => 'Despachante'],
            ['profissao' => 'Agente de Viagens', 'profissaoM' => 'Agente de Viagens', 'profissaoF' => 'Agente de Viagens'],
            ['profissao' => 'Vendedor(a)', 'profissaoM' => 'Vendedor', 'profissaoF' => 'Vendedora'],
            ['profissao' => 'Músico(a)', 'profissaoM' => 'Músico', 'profissaoF' => 'Música'],
            ['profissao' => 'Cantor(a)', 'profissaoM' => 'Cantor', 'profissaoF' => 'Cantora'],
            ['profissao' => 'Compositor(a)', 'profissaoM' => 'Compositor', 'profissaoF' => 'Compositora'],
            ['profissao' => 'Ator/Atriz', 'profissaoM' => 'Ator', 'profissaoF' => 'Atriz'],
            ['profissao' => 'Comediante', 'profissaoM' => 'Comediante', 'profissaoF' => 'Comediante'],
            ['profissao' => 'Artista Plástico', 'profissaoM' => 'Artista Plástico', 'profissaoF' => 'Artista Plástica'],
            ['profissao' => 'Poeta', 'profissaoM' => 'Poeta', 'profissaoF' => 'Poeta'],
            ['profissao' => 'Escritor(a)', 'profissaoM' => 'Escritor', 'profissaoF' => 'Escritora'],
            ['profissao' => 'Jornalista', 'profissaoM' => 'Jornalista', 'profissaoF' => 'Jornalista'],
            ['profissao' => 'Atleta', 'profissaoM' => 'Atleta', 'profissaoF' => 'Atleta'],
            ['profissao' => 'Executivo', 'profissaoM' => 'Executivo', 'profissaoF' => 'Executiva'],
            ['profissao' => 'Do Lar', 'profissaoM' => 'Do Lar', 'profissaoF' => 'Do Lar'],
            ['profissao' => 'Aposentado(a)', 'profissaoM' => 'Aposentado', 'profissaoF' => 'Aposentada'],
            ['profissao' => 'Agricultor(a)', 'profissaoM' => 'Agricultor', 'profissaoF' => 'Agricultora'],
            ['profissao' => 'Investidor(a)', 'profissaoM' => 'Investidor', 'profissaoF' => 'Investidora'],
            ['profissao' => 'Cientista', 'profissaoM' => 'Cientista', 'profissaoF' => 'Cientista'],
            ['profissao' => 'Pesquisador(a)', 'profissaoM' => 'Pesquisador', 'profissaoF' => 'Pesquisadora'],
            ['profissao' => 'Historiador(a)', 'profissaoM' => 'Historiador', 'profissaoF' => 'Historiadora'],
            ['profissao' => 'Geógrafo(a)', 'profissaoM' => 'Geógrafo', 'profissaoF' => 'Geógrafa'],
            ['profissao' => 'Economista', 'profissaoM' => 'Economista', 'profissaoF' => 'Economista'],
            ['profissao' => 'Político(a)', 'profissaoM' => 'Político', 'profissaoF' => 'Política'],
            ['profissao' => 'Matemático(a)', 'profissaoM' => 'Matemático', 'profissaoF' => 'Matemática'],
            ['profissao' => 'Químico(a)', 'profissaoM' => 'Químico', 'profissaoF' => 'Química'],
            ['profissao' => 'Filósofo(a)', 'profissaoM' => 'Filósofo', 'profissaoF' => 'Filósofa'],
            ['profissao' => 'Sociólogo(a)', 'profissaoM' => 'Sociólogo', 'profissaoF' => 'Socióloga'],
            ['profissao' => 'Administrador(a)', 'profissaoM' => 'Administrador', 'profissaoF' => 'Administradora'],
            ['profissao' => 'Faxineiro(a)', 'profissaoM' => 'Faxineiro', 'profissaoF' => 'Faxineira'],
            ['profissao' => 'Coletor(a) de Reciclagem', 'profissaoM' => 'Coletor de Reciclagem', 'profissaoF' => 'Coletora de Reciclagem'],
            ['profissao' => 'Babá', 'profissaoM' => 'Babá', 'profissaoF' => 'Babá'],
            ['profissao' => 'Personal Trainer', 'profissaoM' => 'Personal Trainer', 'profissaoF' => 'Personal Trainer'],
            ['profissao' => 'Corretor(a) de Imóveis', 'profissaoM' => 'Corretor de Imóveis', 'profissaoF' => 'Corretora de Imóveis'],
            ['profissao' => 'Corretor(a) de Investimentos', 'profissaoM' => 'Corretor de Investimentos', 'profissaoF' => 'Corretora de Investimentos'],
            ['profissao' => 'Militar', 'profissaoM' => 'Militar', 'profissaoF' => 'Militar'],
            ['profissao' => 'Policial', 'profissaoM' => 'Policial', 'profissaoF' => 'Policial'],
            ['profissao' => 'Bombeiro(a)', 'profissaoM' => 'Bombeiro', 'profissaoF' => 'Bombeira'],
            ['profissao' => 'Bombeiro(a) Civil', 'profissaoM' => 'Bombeiro Civil', 'profissaoF' => 'Bombeira Civil'],
            ['profissao' => 'Comerciante', 'profissaoM' => 'Comerciante', 'profissaoF' => 'Comerciante'],
            ['profissao' => 'Mecânico(a)', 'profissaoM' => 'Mecânico', 'profissaoF' => 'Mecânica'],
            ['profissao' => 'Náutico(a)', 'profissaoM' => 'Náutico', 'profissaoF' => 'Náutica'],
            ['profissao' => 'Síndico(a)', 'profissaoM' => 'Síndico', 'profissaoF' => 'Síndica'],
            ['profissao' => 'Técnico(a) em Eletrônica', 'profissaoM' => 'Técnico em Eletrônica', 'profissaoF' => 'Técnica em Eletrônica'],
            ['profissao' => 'Técnico(a) em Mecatrônica', 'profissaoM' => 'Técnico em Mecatrônica', 'profissaoF' => 'Técnica em Mecatrônica'],
            ['profissao' => 'Religioso(a)', 'profissaoM' => 'Religioso', 'profissaoF' => 'Religiosa'],
            ['profissao' => 'Garçon/Garçonete', 'profissaoM' => 'Garçon', 'profissaoF' => 'Garçonete'],
            ['profissao' => 'Motoboy/Motogirl', 'profissaoM' => 'Motoboy', 'profissaoF' => 'Motogirl'],
            ['profissao' => 'Gerente', 'profissaoM' => 'Gerente', 'profissaoF' => 'Gerente'],
            ['profissao' => 'Diretor(a) de Empresa', 'profissaoM' => 'Diretor de Empresa', 'profissaoF' => 'Diretora de Empresa'],
            ['profissao' => 'Diretor(a) de Escola', 'profissaoM' => 'Diretor de Escola', 'profissaoF' => 'Diretora de Escola'],
            ['profissao' => 'Inspetor(a) de Alunos', 'profissaoM' => 'Inspetor de Alunos', 'profissaoF' => 'Inspetora de Alunos'],
            ['profissao' => 'Manobrista', 'profissaoM' => 'Manobrista', 'profissaoF' => 'Manobrista'],
            ['profissao' => 'Frentista', 'profissaoM' => 'Frentista', 'profissaoF' => 'Frentista'],
            ['profissao' => 'Caminhoneiro(a)', 'profissaoM' => 'Caminhoneiro', 'profissaoF' => 'Caminhoneira'],
            ['profissao' => 'Publicitário(a)', 'profissaoM' => 'Publicitário', 'profissaoF' => 'Publicitária'],
            ['profissao' => 'Produtor(a) Digital', 'profissaoM' => 'Produtor Digital', 'profissaoF' => 'Produtora Digital'],
            ['profissao' => 'Marinheiro(a)', 'profissaoM' => 'Marinheiro', 'profissaoF' => 'Marinheira'],
            ['profissao' => 'Secretário(a)', 'profissaoM' => 'Secretário', 'profissaoF' => 'Secretária'],
            ['profissao' => 'Recepcionista', 'profissaoM' => 'Recepcionista', 'profissaoF' => 'Recepcionista'],
            ['profissao' => 'Caixa', 'profissaoM' => 'Caixa', 'profissaoF' => 'Caixa'],
            ['profissao' => 'Estoquista', 'profissaoM' => 'Estoquista', 'profissaoF' => 'Estoquista'],
            ['profissao' => 'Marceneiro(a)', 'profissaoM' => 'Marceneiro', 'profissaoF' => 'Marceneira'],
            ['profissao' => 'Refrigerista', 'profissaoM' => 'Refrigerista', 'profissaoF' => 'Refrigerista'],
            ['profissao' => 'Vidraceiro(a)', 'profissaoM' => 'Vidraceiro', 'profissaoF' => 'Vidraceira'],
            ['profissao' => 'Confeiteiro(a)', 'profissaoM' => 'Confeiteiro', 'profissaoF' => 'Confeiteira'],
            ['profissao' => 'Tapeceiro(a)', 'profissaoM' => 'Tapeceiro', 'profissaoF' => 'Tapeceira'],
            ['profissao' => 'Desempregado(a)', 'profissaoM' => 'Desempregado', 'profissaoF' => 'Desempregada'],
        ];

        foreach ($profissoes as $profissao) {
            Occupation::create($profissao);
        }
    }
}
